#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
debug: true
#名称
server_name: "mail2listWeb"
#server 地址
server:
  host: "0.0.0.0"
  port: "9999"
#数据库地址
database_url: "postgresql://${OPENGUASS_USER}:${OPENGUASS_PWD}@${OPENGUASS_URL}:${OPENGUASS_PORT}/mail2list"
#逻辑删除字段
logic_column: "del"
logic_un_deleted: 0
logic_deleted: 1
#日志文件存放目录
log_dir: "target/logs/"
#日志分割尺寸-单位KB,MB,GB
log_temp_size: "100MB"
#日志打包格式可选“”（空-不压缩）“gzip”（gz压缩包）“zip”（zip压缩包）“lz4”（lz4压缩包（非常快））
log_pack_compress: "zip"
#日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
log_rolling_type: "KeepNum(20)"
#日志等级-info,error,warn,debug,trace
log_level: "info"

email:
  #此处应该是一个数组 密码以及服务等都应该是一个数组 来对应多个服务
  #这是代表订阅邮箱的地址
  mine_email: ${mine_email}
  smtp_server: ${smtp_server}
  password: ${password}
  imap_server: ${imap_server}
  #这是代表归档邮箱的地址
  archive_mine_email: ${archive_mine_email}
  archive_smtp_server: ${archive_smtp_server}
  archive_password: ${archive_password}
  archive_name: ${archive_name}
  archive_imap_server: ${archive_imap_server}
  #一个退订邮箱管理一个社区
  leave_email : ${leave_email}
  leave_email_password : ${leave_email_password}
  leave_name: ${leave_name}
  leave_smtp_server: ${leave_smtp_server}
  leave_imap_server: ${leave_imap_server}